<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WaliMuridSeeder2 extends Seeder
{
    public function run(): void
    {
        DB::table('walimurid')->insert([
            [
                'nama_walimurid'   => 'Sukadi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Darmo',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Majid',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Zaini',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Kuwati',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Daman',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Heru Susanto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid'   => 'Siti Sofiyah',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            ['nama_walimurid' => 'Warjito',          'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Sugin',            'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Mashuri',          'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Sugeng',           'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Darmi Rusdi',      'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Muhdorin',         'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Satrisno',         'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Kasdi Purnomo',    'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'Kusnadi',          'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            ['nama_walimurid' => 'G. Darmoko',       'telpon_walimurid' => null, 'email_walimurid' => null, 'alamat_walimurid' => null, 'reg_code' => null, 'reg_code_expires' => null, 'created_at' => now(), 'updated_at' => now(),],
            [
                'nama_walimurid' => 'Syarofah Ida Nurul Khomaini',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Dwi Irnawan',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Laminto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Suwarno',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Siti Zulaikah',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Supriadi AT',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Suyono',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Eva Surya Ningsih',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Agustinus Supriyadi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'SUGIONO',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'JAINI',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Supandi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'SUGIARNO',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'NURHADI',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Katemin',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'PANIMIN',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'JOKO UMBARAN',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Suwadi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Fajar Wibowo',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Salimin',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Aliy',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Mariyanto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sutarno',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Yuli Priyanto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Komsatun',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sulistyono',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'BAMBANG IRAWAN',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Slamet',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Agus Mulyono',          // diambil dari kolom “Nama Wali”
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'JOKO SATRIO BAGUS',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'SYAIFUL HIDAYAT',       // diambil dari kolom “Nama Wali”
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'KUSNAN',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'SOETIYO',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Slamet Aryadi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Umi Rubiatin',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Bambang Hermanto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Turyanto',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sukandar',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sumadi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sumaryono',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Waji',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'KUSNAN',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'nama_walimurid' => 'Sunardi',
                'telpon_walimurid' => null,
                'email_walimurid'  => null,
                'alamat_walimurid' => null,
                'reg_code'         => null,
                'reg_code_expires' => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ]);
    }
}
